spring:
  # datasource:
      # driver-class-name: com.mysql.cj.jdbc.Driver
      # url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      # username: root
      # password: 'cjb0402^^'

  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

# 애초에 memory가 디폴트라 위 코드 없어도 됨!!
# ddl-auto는 디폴트가 create-drop -> 프로그램 종료 시 모든 생성 테이블을 드랍해버림

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩
  secret: KLwq6ankmcBgh0rA/z5mc67pShboxiOICIUT23Do5TT9hBRPcSH3T7h0SUetWBzAl8YyW1q1AYtwn2OYE52P2w==
